"""migration

Revision ID: 788d8897bd02
Revises: 
Create Date: 2025-05-21 19:48:30.619092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788d8897bd02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=200), nullable=True),
    sa.Column('driver', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
