"""new]

Revision ID: 9307d8bea3e5
Revises: 18e5eb6d7a90
Create Date: 2025-05-20 11:29:29.660458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9307d8bea3e5'
down_revision = '18e5eb6d7a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ride_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('driver', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('feedback_customer_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ride_id'])
        batch_op.drop_column('dealer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('feedback_customer_key', ['customer'])
        batch_op.drop_column('driver')
        batch_op.drop_column('ride_id')

    # ### end Alembic commands ###
